### ISSUE TITLE
"Resources" folder not configurable

### ISSUE THREAD

**Issue by stevie-mayhew** [silverstripe/vendor-plugin#14]
Currently the "resources" folder structure ends up meaning that the path "/resources" is not available for page URL segments within the site.

The "resources" folder pathway should be configurable so that instances where a "/resources" URL segment is required is achievable. 

Additionally, a system to notify that a URL is unavailable should be implemented so that CMS authors are not confused.

**Comment by tractorcow** [comment]
We'll change this to another hard-coded path in 5.0, something which should hopefully not clash with real urlsegments, but we'll never make this configurable.

**Comment by madmatt** [comment]
Is there a particular reason why it can't be configurable? It already seems to be based on a const (`ManifestFileFinder.RESOURCES_DIR`).

**Comment by stevie-mayhew** [comment]
Looks like this is completed in #26

**Comment by maxime-rainville** [comment]
We didn't touch this point thought:
> Additionally, a system to notify that a URL is unavailable should be implemented so that CMS authors are not confused.

**Comment by stevie-mayhew** [comment]
@maxime-rainville I think that sits within the implementation outside this module? Its a side effect of the usage of this module elsewhere.

I'm not sure if its something we want to handle as part of `admin` or the core framework though?

**Comment by maxime-rainville** [comment]
It probably would go in CMS. Right now, if you try to assign `resources` to a page, it just silently gets renames to `resources-2`.
