### ISSUE TITLE
"auto" method determining to use symlinks rather than copying

### ISSUE THREAD

**Issue by rohitbanerjee** [silverstripe/vendor-plugin#15]
## Affected Version
silverstripe 4.0.3
Output of `composer info --direct`.
## Description
Using the script `composer create-project silverstripe/installer ./` and `composer require silverstripe/<any-compatible-ss4-module>` on a Windows 10 based XAMPP environment, gives vendor-expose error as below, where the auto" method is determining to use symlinks rather than copying. Probably the vendor-plugin "auto" isn't working correctly.

```
Exposing web directories for silverstripe-vendormodule silverstripe/framework with method auto:   
- client/images   
- client/styles   
- src/Dev/Install/client

[ErrorException]
copy(D:\xampp\htdocs\test-site\vendor\silverstripe\framework\client\images): failed to open stream: No such file or directory
```

The (sym)link to the "image" folder is not being created in the final deployment path.

**Comment by JorisDebonnet** [comment]
The auto method on Windows will usually try a Junction first, but if that fails, try a copy instead. I think your error message means both types failed. 

Could you try again running the script with Administrator privileges, seeing whether that solves the issue?

**Comment by dhensby** [comment]
No feedback for 4 months
