### ISSUE TITLE
Exposed directories don't work correctly for relative-path dependencies

### ISSUE THREAD

**Issue by scott1702** [silverstripe/vendor-plugin#20]
When composer dependencies are installed from [relative paths](https://getcomposer.org/doc/05-repositories.md#path), directories listed in the dependency's `expose` are not accessible in the expected public path

**Comment by maxime-rainville** [comment]
That's probably got something to do with the symlinking of of folders. Did you try using the `symlink` option in your composer file?
```json
{
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "options": {
                "symlink": false
            }
        }
    ]
}
```

Does using a [custom behavior](https://github.com/silverstripe/vendor-plugin#customising-behaviour) affect this issue?

**Comment by Zauberfisch** [comment]
Probably same bug as #34. I'd vote to close
