### ISSUE TITLE
Composer 2 will fail to install this plugin as it requires plugin version ^2.0

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/vendor-plugin#31]
See equivalent issue against recipe-plugin: https://github.com/silverstripe/recipe-plugin/issues/15

Upgrading guide here: https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#user-content-for-integrators-and-plugin-authors

**Comment by sminnee** [comment]
Fix at #36

**Comment by Cheddam** [comment]
#36 has been merged.
