### ISSUE TITLE
Support "expose" in themes

### ISSUE THREAD

**Issue by chillu** [silverstripe/vendor-plugin#4]
This only applies for themes which are pulled in via composer. Which not a lot of people do in practice - they just inline the theme in the main repo. It's important anyway to solve this, since we can't move the webroot to a `public/` folder in the default installer unless the `simple` theme can copy files there.

# Notes

 * Track under ORB-157

**Comment by tractorcow** [comment]
I would just provide a vendormodule as a theme and then use the composer name instead of `themes` dir name

`vendor/silverstripe-themes/simple` can be specified with:

```SSViewer:
  themes:
    - silverstripe-themes/simple
    - '$default'
```

**Comment by chillu** [comment]
As discussed with Damian before, that approach will only work for themes which are actual composer packages. For inlined themes, we agreed that a wildcarded expose in the root `composer.json` is the most dev friendly default:

```
"extra": {
  "expose": [
    "themes/*/css",
    "themes/*/js"
  ]
}
```

There's no composer lifecycle trigger for this, the folder contents could change at any time. Damian suggested linking this via `dev/build`, but that'll have to be opt out: In many hosting platforms, you can't run file modification operations like these in production (they might only apply to a single webserver of a load balanced setup).

**Comment by tractorcow** [comment]
My new suggestion is to split the core of this plugin out to a separate library, and make this library a dependency of framework. "expose" will then be enabled on silverstripe-module and silverstripe-theme as well as silverstripe-vendormodule.

**Comment by tractorcow** [comment]
@andrewandante you can put an `expose` pointing to the relative path to your resource, but in your project root.

E.g.

```json
"expose": [
	"themes/mytheme/client"
]
```

**Comment by tractorcow** [comment]
Oh, you can also just commit directly to the public directory.

e.g.

`public/css`

And then make sure that `$public` is in your theme config.

See the changelog note https://docs.silverstripe.org/en/4/changelogs/4.1.0/#use-new-public-theme-set

We need to improve the theme docs to show this. https://docs.silverstripe.org/en/4/developer_guides/templates/themes/

**Comment by andrewandante** [comment]
@tractorcow thanks - I spent a little of the afternoon toying with it (working with a user on the SS Users Slack) and one of the key findings was that I needed to set 

```json
"type": "silverstripe-recipe"
```

in my main `composer.json` for the `vendor-expose` to work. This should be mentioned as well, because not everyone is starting from a recipe base.

It's a _little_ unintuitive to have part of your theme in `public` and part of it in `themes/mytheme` - so I think the way that makes the most sense is to use the full path in `"extra":{"expose":[]}` and add the type line, especially as a first recommendation.

Thanks for clarifying though, big help 😃

**Comment by tractorcow** [comment]
Oh, that's a good idea. We should remove the base recipe type limitation.

**Comment by tractorcow** [comment]
Actually, we've already implemented theme expose.

https://github.com/silverstripe-themes/silverstripe-simple/pull/51

Not sure why this PR was still open. :)

**Comment by tractorcow** [comment]
Also https://github.com/silverstripe/vendor-plugin/pull/18
