### ISSUE TITLE
Remove 1 branch, resolve outdated branch alias in master

### ISSUE THREAD

**Issue by chillu** [silverstripe/vendor-plugin#41]
The `1` branch is where most improvements happen, and [slightly ahead](https://github.com/silverstripe/vendor-plugin/compare/1...master) of master. `master` has a branch-alias of `1.3.x-dev`, which is lagging far behind the actual tags (up to `1.5.1`). I've seen some really weird constraint failures in composer because of this (sorry, don't have the exact message or circumstances).

We could set this branch alias to `2.x-dev`, but I would argue that there's no reason for this until we actually want to make breaking changes. Instead, my recommendation would be to merge `1` into `master`, delete the `1` branch, and change the branch-alias in `master` to `1.x-dev`.

**Comment by GuySartorelli** [comment]
Closed in favour of https://github.com/silverstripe/silverstripe-framework/issues/10349
