### ISSUE TITLE
Gracefully handle paths with trailing slashes

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/vendor-plugin#44]
Ran into an issue on https://github.com/silverstripe/silverstripe-graphql-devtools/pull/38, but it can happen anywhere.

When an exposed path entry ends with a slash, some unix systems can't handle that as a symlink. If there's even one entry like that in the set of exposed folders, the logic falls back to using the copy approach, silently. That may lead to expectations that content gets automatically updated in the exposed folder and it, in fact, doesn't.

We can either return an early warning to remove all trailing slashes, which might be a pita when it's coming from a 3rd party module such as the one linked above. Gracefully removing trailing slashes before the exposed paths are used would be nicer, I guess.

**Comment by emteknetnz** [comment]
> some unix systems can't handle that as a symlink

could you elaborate what that means?  which unix systems?

**Comment by michalkleiner** [comment]
It was happening in our docker env setup using alpine base image IIRC. I'll try to narrow it down a bit more, however, the issue still stands regardless — if symlink can't be created for a single entry, all other entries fallback to using the copy method silently.

**Comment by michalkleiner** [comment]
Ok, now I remember. The issue is when the entry in the expose list ends with a slash, it's trying to create a symlink where the destination also ends with a slash, which is not a valid way to define the name for the symlink.

On Mac:
![Screen Shot 2021-05-14 at 3 11 30 PM](https://user-images.githubusercontent.com/233342/118216052-e1380000-b4c6-11eb-8ce7-556f1ae83538.png)

**Comment by michalkleiner** [comment]
Related PR merged, closing.
