### ISSUE TITLE
Fatal error if composer.json is missing in a composer package

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/vendor-plugin#48]
Some composer packages add `composer.json` to their `.gitattributes` file:

```
composer.json export-ignore
```

I have no idea why anyone would do this, but people like to do weird things apparently.

When this is set, composer will install the package without composer.json being present, which results in a fatal error because the following code assumes it’s always there:

https://github.com/silverstripe/vendor-plugin/blob/a0f963b66f5ae93841ccca85d7074339c6ce65c7/src/Library.php#L187-L189

### PR
- [ ] https://github.com/silverstripe/vendor-plugin/pull/49

**Comment by emteknetnz** [comment]
This seems ridiculous :-)

Could you provide an example of "some composer packages"

**Comment by kinglozzer** [comment]
I agree it’s definitely odd, I’m not sure whether composer allows it or not! We inherited a project which uses this library:

https://github.com/JamesHeinrich/getID3
https://github.com/JamesHeinrich/getID3/blob/master/.gitattributes#L30

**Comment by emteknetnz** [comment]
https://github.com/silverstripe/vendor-plugin/pull/49
