### ISSUE TITLE
Need for `compser vendor-rebuild` command to regenerate vendor links.

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/vendor-plugin#9]
From https://github.com/silverstripe/silverstripe-installer/issues/206#issuecomment-344076215, it would be useful to take advantage of composer plugin's ability to extend the command list with one which rebuild the resources folder.

We have done something similar with the recipe-plugin: https://github.com/silverstripe/recipe-plugin/blob/master/src/UpdateRecipeCommand.php

**Comment by chillu** [comment]
@tractorcow How many points do you estimate for this?

**Comment by tractorcow** [comment]
3

**Comment by flamerohr** [comment]
This has been addressed with https://app.zenhub.com/workspace/o/silverstripe/silverstripe-installer/issues/206
